// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukwqopozwbdwcdjdorzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrd3FvcG96d2Jkd2NkamRvcnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjg5OTYsImV4cCI6MjA2NTY0NDk5Nn0.nG7DcGRVdO92zUeYaNhqVLitWwwmMHyPOPSGZLcwsBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);